### ISSUE TITLE
Support IPv4 for Devices in Out-of-Band Network

### ISSUE THREAD

**Issue by hardikdr** [ironcore-dev/FeDHCP#165]
# Summary

Enhance FeDHCP to support IPv4 for devices within the out-of-band (OOB) network, ensuring compatibility with existing plugins.

## Motivation

Better flexibility, and support more device configurations.

**Comment by damyan** [comment]
We already support IPv4 in our [OOB plugin](https://github.com/ironcore-dev/FeDHCP/blob/main/plugins/oob/plugin.go#L117). 

> Note:Major difference to IPv6 OOB is, that we do *not* rely on relays in IPv4 (for now). To work around different multicast domains in kubernetes, we run with `hostNetwork: true`, so OOB IPv4 traffic reaches the pod.
